### ISSUE TITLE
Checkpoint #2

### ISSUE THREAD

**Issue by redfoxanna** [redfoxanna/diamond-poems#6]
Hi @pawaitemadisoncollege, I just pushed all my code up to my diamond-poem repo for you to take a look at!

**Comment by pawaitemadisoncollege** [comment]
Hi @redfoxanna! Great job hitting checkpoint 2 from the DAO/Hibernate standpoint! Completing the work each week in your project set you up really well here! 

- [x]  Can you add an image of your ERD so that I can review and provide any feedback (if this is here already and I overlooked it, please let me know). If you don't have a preferred way to create the erd, you can generate it out of the database view in IntelliJ. I think the sequence is right click on the db, then diagrams. I realize I should have been more clear about including this for this CP.

- [x] You've been doing a good job updating your journal as you complete work.  What do you think about adding an indicator in your project plan for what is complete?  Related to the plan, if you haven't reviewed and updated your plan recently for the final 8 weeks, this would be a good time to do that, since you now have all the learning on new topics need for the project (or will have in the next few days).

- [x] I think I mentioned this in the peer code review issue, but wanted to highlight it here as well since log4j/noprintlns is part of cp 2: https://github.com/search?q=repo%3Aredfoxanna%2Fdiamond-poems%20print&type=code

- [x] Looks like you've added the genericdao! Can you remove the entity-specific daos at this point? Don't worry, if you delete them, they are still "findable" in your GitHub history. 

- [x] I did a little poking around, mostly to look for best practices, and noticed that there were a few directives that I think you should be able to replace with the jstl import tag? One example: https://github.com/redfoxanna/diamond-poems/blob/296b5bcb84d43b2be2d0411a50c2badd35fd9f08/src/main/webapp/poem-search.jsp#L3

I'm going to mark this as "not yet" in blackboard mostly as a reminder to myself that I need to review the ERD yet.

**Comment by redfoxanna** [comment]
Hi @pawaitemadisoncollege, thanks for the feedback! I was able to generate a diagram in IntelliJ and added it to my design documents. I will work on the rest of this on break  :-) 
https://github.com/redfoxanna/diamond-poems/blob/main/DesignDocuments/ERD.png

**Comment by pawaitemadisoncollege** [comment]
Hi @redfoxanna - Thanks for sharing the ERD! No big concerns here, though I think there is opportunity here to add a table for the tags/genre. 

The benefits of adding that table: it will remove some possible duplicate values from the table (normalizing), might provide faster searching (show me all the poems with the tag of "whatever"),  and will provide you with a way to add an additional relationship. One of the "requirements" of the project is to have multiple one-to-many relationships, BUT if you don't have this, it is not the end of the world. I listed that as requirement as it would be a way to further demonstrate your proficiency with hibernate beyond what we did in the user-display exercise/demo. The team project will be another place to demonstrate this.
